use_frameworks!

platform :ios, '8.0'

target 'HLSAudioPlayer_Example' do
  pod 'HLSAudioPlayer', :path => '../'

  target 'HLSAudioPlayer_Tests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end
end
