osx_image: xcode10
language: objective-c
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/HLSAudioPlayer.xcworkspace -scheme HLSAudioPlayer-Example -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
- sleep 5
